import '../models/store.dart';
import '../models/basket.dart';

class DummyData {
  static final List<Store> stores = [
    Store(
      id: 's1',
      name: 'Boulangerie Nour',
      category: 'Boulangerie',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
      address: '12 Rue Larbi Ben M\'hidi, Oran',
      rating: 4.8,
      distance: 0.3,
    ),
    Store(
      id: 's2',
      name: 'Restaurant Dar Zitoun',
      category: 'Cuisine Algérienne',
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
      address: '45 Avenue Mohammed V, Oran',
      rating: 4.7,
      distance: 0.7,
    ),
    Store(
      id: 's3',
      name: 'Pâtisserie El Warda',
      category: 'Pâtisserie Orientale',
      imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400',
      address: '8 Rue des Frères Bouadou, Oran',
      rating: 4.9,
      distance: 0.5,
    ),
    Store(
      id: 's4',
      name: 'Marché Bio Wahran',
      category: 'Épicerie',
      imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
      address: '23 Boulevard Zabana, Oran',
      rating: 4.5,
      distance: 1.1,
    ),
    Store(
      id: 's5',
      name: 'Snack El Djazair',
      category: 'Fast-food',
      imageUrl: 'https://images.unsplash.com/photo-1561651188-d207bbec4ec3?w=400',
      address: '5 Rue Khemisti, Oran',
      rating: 4.3,
      distance: 0.9,
    ),
    Store(
      id: 's6',
      name: 'Café Tlemcen',
      category: 'Café',
      imageUrl: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=400',
      address: '17 Place du 1er Novembre, Oran',
      rating: 4.6,
      distance: 0.4,
    ),
  ];

  static final List<Basket> baskets = [
    Basket(
      id: 'b1',
      title: 'Panier Viennoiseries',
      description: 'Msemen croustillants, baghrir moelleux, miel et beurre. Le petit déj parfait !',
      imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400',
      originalPrice: 900.0,
      discountedPrice: 350.0,
      totalSlots: 5,
      remainingSlots: 2,
      pickupStart: DateTime.now().add(const Duration(hours: 1)),
      pickupEnd: DateTime.now().add(const Duration(hours: 3)),
      store: stores[0],
      isFavorite: true,
    ),
    Basket(
      id: 'b2',
      title: 'Panier Couscous & Tajine',
      description: 'Couscous au poulet, tajine zitoune et soupe harira. Un vrai repas algérien !',
      imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400',
      originalPrice: 2500.0,
      discountedPrice: 800.0,
      totalSlots: 3,
      remainingSlots: 1,
      pickupStart: DateTime.now().add(const Duration(hours: 2)),
      pickupEnd: DateTime.now().add(const Duration(hours: 4)),
      store: stores[1],
    ),
    Basket(
      id: 'b3',
      title: 'Panier Pâtisseries Orientales',
      description: 'Baklava, makroud, qalb el louz et cornes de gazelle.',
      imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400',
      originalPrice: 1500.0,
      discountedPrice: 500.0,
      totalSlots: 4,
      remainingSlots: 3,
      pickupStart: DateTime.now().add(const Duration(hours: 1)),
      pickupEnd: DateTime.now().add(const Duration(hours: 3)),
      store: stores[2],
      isFavorite: true,
    ),
    Basket(
      id: 'b4',
      title: 'Panier Légumes Frais',
      description: 'Tomates, courgettes, poivrons et herbes fraîches du marché local.',
      imageUrl: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=400',
      originalPrice: 1200.0,
      discountedPrice: 400.0,
      totalSlots: 6,
      remainingSlots: 4,
      pickupStart: DateTime.now().add(const Duration(hours: 1)),
      pickupEnd: DateTime.now().add(const Duration(hours: 2)),
      store: stores[3],
    ),
    Basket(
      id: 'b5',
      title: 'Panier Merguez & Sandwichs',
      description: 'Sandwichs merguez grillées, fricassé et boissons. Le snack du soir !',
      imageUrl: 'https://images.unsplash.com/photo-1561651188-d207bbec4ec3?w=400',
      originalPrice: 900.0,
      discountedPrice: 300.0,
      totalSlots: 5,
      remainingSlots: 2,
      pickupStart: DateTime.now().add(const Duration(hours: 3)),
      pickupEnd: DateTime.now().add(const Duration(hours: 5)),
      store: stores[4],
    ),
    Basket(
      id: 'b6',
      title: 'Panier Café & Gâteaux',
      description: 'Café turc, thé à la menthe et assortiment de petits gâteaux maison.',
      imageUrl: 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=400',
      originalPrice: 700.0,
      discountedPrice: 200.0,
      totalSlots: 4,
      remainingSlots: 3,
      pickupStart: DateTime.now().add(const Duration(hours: 2)),
      pickupEnd: DateTime.now().add(const Duration(hours: 4)),
      store: stores[5],
    ),
  ];
}